project:
  type: book

book:
  title: "理论天体物理学笔记"
  author: "吕天宁"
  date: "9/24/2025"
  chapters:
    - index.qmd
    - kinetics.qmd
    - references.qmd

# bibliography: references.bib
execute:
  freeze: auto

format:
  html:
    theme: cosmo



