# 动理学理论
## 分布函数
经典力学中，粒子的位置$\mathbf{x}$和动量$\mathbf{p}$完全决定其状态。因此，相空间中的一点$(\mathbf{x},\mathbf{p})$可完全确定其力学状态。为描述粒子在相空间中的分布，引入分布函数的概念。

定义数密度分布函数。若相空间体积元$\mathrm{d}^{3} u \mathrm{d}^{3} v$中粒子的数目为$\mathrm{d}N$，则分布函数$f(\mathbf{x},\mathbf{u},t)$满足:

$$ \mathrm{d} N=f(\mathbf{x},\mathbf{u},t) \mathrm{d}^3 u \mathrm{d}^3 v $$ {#eq-df}

显然其在整个相空间内的积分将满足归一化条件，等于粒子总数：
$$N_{\text{tot}} = \int_{\mathbb{R}^3} \int_{\mathbb{R}^3} f \, d^3x \, d^3u $${#eq-norm}

也可完全类似地定义质量密度分布函数（归一化为总质量）、概率密度分布函数（归一化为1）。

分布函数描述的是粒子的微观分布，要得到宏观物理量，可以利用对分布函数求速度矩的方法。一般地，分布函数的速度矩定义为

$$Q(\mathbf{x},t)=\int_{\mathbb{R}^3}q(\mathbf{u},t)\left.f(\mathbf{x},\mathbf{u},t)\right.\mathrm{d}^3u$${#eq-moments}

其中$Q(\mathbf{x},t)$是粒子速度的函数。

下面具体讨论分布函数的0阶、1阶、2阶矩。

0阶矩：将分布函数对速度空间积分，可得到数密度。

$$n(\mathbf{x},t)=\int_{\mathbb{R}^3} f(\mathbf{x},\mathbf{u},t)\mathrm{d}^3 u$${#eq-ndensity}

乘上粒子质量便可得到质量密度：

$$\rho(\mathbf{x},t)=mn(\mathbf{x},t)$${#eq-massdensity}

1阶矩：动量密度

$$\mathbf{m}(\mathbf{x},t)=\int_{\mathbb{R}^3}mf(\mathbf{x},\mathbf{u},t)\mathbf{u}\mathrm{d}^3 u$${#eq-momentumdensity}

由此定义流体的宏观速度$\mathbf{v}(\mathbf{x},t)$

$$\mathbf{m}(\mathbf{x},t)=\rho(\mathbf{x},t) \mathbf{v}(\mathbf{x},t)$${#eq-bulk}

于是可以定义微观相对速度，即热速度

$$\mathbf{w}=\mathbf{u}-\mathbf{v}$${#eq-thermal}

热速度可以理解为速度的涨落，从物理图像直观上便可猜测分布函数数乘它然后对整个速度空间积分为0。严格的数学推导也并不难，引用 @eq-momentumdensity、@eq-bulk、@eq-ndensity ，可以得到

$$\int f\mathbf{u} \mathrm{d}^3 u=\frac{\rho}{m}\mathbf{v}=n\mathbf{v}$$ {#eq-fud3u}

$$\int f\mathbf{v} \mathrm{d}^3 u=n\mathbf{v}$$ {#eq-fvd3u}

于是

$$\int f\mathbf{w} \mathrm{d}^3 u=\int f\mathbf{u} \mathrm{d}^3 u-\int f\mathbf{v} \mathrm{d}^3 u=n\mathbf{v}-n\mathbf{v}=0$$ {#eq-fwd3u}

这在我们推导二阶矩（能量密度）的一个有用形式时会被用到。

2阶矩：能量密度

$$E(\mathbf{x},t)=\int_{\mathbb{R}^3}\frac{1}{2}m\left.u^2\right.f(\mathbf{x},\mathbf{u},t)\operatorname{d}^3u$$ {#eq-energydensity}

将速度分解为宏观速度与热速度两部分，即$\mathbf{u}=\mathbf{w}+\mathbf{v}$，可以将上式写作

$$E(\mathbf{x},t)=\frac{1}{2}m\int w^2f\mathrm{d}^3u+m\mathbf{v}\cdot\int \mathbf{w}f\mathrm{d}^3u+\frac{1}{2}mv^2\int f\mathrm{d}^3u$$ {#eq-E(x,t)}

注意$\mathbf{v}(\mathbf{x},t)$仅是位置与时间的函数，与速度$\mathbf{u}$无关，所以在对速度空间积分时可以直接提出到积分符号外。利用我们前面证明的结论，第二项为0.

定义各个分量上的速度弥散$\sigma_{i}(\mathbf{x},t)$：

$$n(\mathbf{x},t)\sigma_i^2(\mathbf{x},t)=\int f(\mathbf{x},\mathbf{u},t) w_i^2 \mathrm{d}^3u$$ {#eq-sigma1D}

定义三维速度弥散$\sigma_{3D}$：

$$\sigma_{\text{3D}}^2=\sigma_{x}^2+\sigma_{y}^2+\sigma_{z}^2$$ {#eq-sigma3D}

可以将能量密度表示成：

$$E(\mathbf{x},t)=\frac{1}{2}\rho\sigma_{\text{3D}}^2+\frac{1}{2}\rho v^2$$ {#eq-Edensity}

## Boltzmann方程
### Liouville定理与Boltzmann方程的导出
考虑6维相空间坐标$\mathbf{z}=(\mathbf{x},\mathbf{u})$，位置与速度互相独立。在极小时间步内，质点在相空间内的轨迹满足：
$$\mathbf{x}=\mathbf{x}_0 +\mathbf{u}_0 dt$$ {#eq-trajectory1}
$$\mathbf{u}=\mathbf{u}_0 + \mathbf{a}(\mathbf{x}_{0}, t_{0})dt$$ {#eq-trajectory2}
考虑一体积元$\mathrm{d}^{6}V_{0}=\mathrm{d}^{3}x_{0}\mathrm{d}^{3}u_{0}$，沿着该轨迹移动到相空间上的新位置，成为新的体积元$\mathrm{d}^{6}V=\mathrm{d}^{3}x\mathrm{d}^{3}u$. 新体积元与原体积元之间由Jacobi行列式联系：
$$\mathrm{d}^{6}V=|\mathbb{J}|\mathrm{d}^{6}V_{0}$$ {#eq-JacobiLink}
$$\mathbb{J}=\frac{\partial(\mathbf{x},\mathbf{u})}{\partial(\mathbf{x}_0,\mathbf{u}_0)}=\begin{pmatrix}\frac{\partial\mathbf{x}}{\partial\mathbf{x}_0}&\frac{\partial\mathbf{x}}{\partial\mathbf{u}_0}\\\frac{\partial\mathbf{u}}{\partial\mathbf{x}_0}&\frac{\partial\mathbf{u}}{\partial\mathbf{u}_0}\end{pmatrix}=\begin{pmatrix}\mathbb{I}&\mathrm{d}t\operatorname{}\mathbb{I}\\\mathrm{d}t\operatorname{}\frac{\partial\mathbf{a}}{\partial\mathbf{x}}&\mathbb{I}\end{pmatrix}$$ {#eq-JacobiMetrix}

注意，此处的Jacobi矩阵是用分块矩阵的形式写出的，每一个“元素”实际上都是一个$3\times 3$矩阵，因此它实际上是一个$6\times 6$矩阵。

左下角元素$\frac{\partial \mathbf{u}}{\partial \mathbf{x}_{0}}$的计算（相较于其他几个元素）并不非常显然，详细写一下步骤。逐分量求偏导数：
$$\frac{\partial u_{i}}{\partial x_{0j}}=\frac{\partial}{\partial x_{0j}}(u_{0i}+a_{i}(\mathbf{x}_{0},t_{0})\mathrm{d}t)$$ {#eq-partial1}
位置与速度是独立变量，故第一项为0，于是
$$\frac{\partial u_{i}}{\partial x_{0j}}=\frac{\partial a_{i}}{\partial x_{0j}}\mathrm{d}t$$ {#eq-partial2}
将全部分量组合即得。

下面进行Jacobi行列式$|\mathbb{J}|$的计算。利用Schur补公式，对于分块行列式$\mathrm{det}\begin{pmatrix}A&B\\C&D\end{pmatrix}$，若矩阵A可逆，有
$$\mathrm{det}\begin{pmatrix}A&B\\C&D\end{pmatrix}=\mathrm{det}(A)\mathrm{det}(D-CA^{-1}B)$$ {#eq-Schur}
可以得到
$$|\mathbb{J}|=\mathrm{det}(\mathbb{I}-\mathrm{d}t^{2}\frac{\partial\mathbf{a}}{\partial\mathbf{x}})$$ {#eq-JacobiCal1}
使用小量展开，当$\epsilon$很小时，
$$\mathrm{det}(\mathbb{I}+\epsilon M)=1+\epsilon \mathrm{tr}M+O(\epsilon^2)$$ {#eq-small}
由此得到
$$|\mathbb{J}|=1-\mathrm{d}t^{2}(\nabla_{\mathbf{x}}\cdot\mathbf{a})+O(\mathrm{d}t^4)$$ {#eq-JacobiCal2}
这里利用了$\frac{\partial\mathbf{a}}{\partial\mathbf{x}}$的迹是$\nabla_{\mathbf{x}}\cdot\mathbf{a}$.

上式表明该Jacobi行列式中小量是二阶及以上的，不含一阶小量。于是
$$\frac{\mathrm{d}^{6} V-\mathrm{d}^{6} V_{0}}{\mathrm{d}t} \simeq -\mathrm{d}^{6} V_{0} (\nabla_{\mathbf{x}}\cdot \mathbf{a})\mathrm{d} t \to 0 \qquad (\mathrm{d}t \to 0)$$ {#eq-derive}
换言之
$$\boxed{\frac{\mathrm{D}}{\mathrm{D}t}(\mathrm{d}^{6} V)=0}$$ {#eq-Liouville}
该公式具有鲜明的物理意义：**相空间的微元体积随流动保持不变**。这就是**Liouville定理**。式中的$\frac{\mathrm{D}}{\mathrm{D}t}$称为**物质导数**，其物理意义是**沿着一条粒子的轨迹$(\mathbf{x}(t),\mathbf{u}(t))$，某函数$f$随时间的变化；即在粒子随流动运动的过程中，所经历的场值的变化率。**

设$f(\mathbf{x},\mathbf{u},t)$是相空间分布函数，相空间“新”体积元内的粒子数为
$$
\mathrm{d}N=f(\mathbf{x},\mathbf{u},t)\mathrm{d}^{3}x\mathrm{d}^{3}u
$$ {#eq-newnumber}

“旧”体积元内的粒子数为
$$
\mathrm{d}N_{0}=f(\mathbf{x}_0,\mathbf{u}_0,t)\mathrm{d}^{3}x_{0}\mathrm{d}^{3}u_{0}
$$ {#eq-oldnumber}

在**没有生成湮灭、没有碰撞换格**的情况下，粒子数是守恒的，而相空间体积元的体积也是守恒的（Liouville定理），于是**分布函数沿单粒子轨道守恒**，即**分布函数的物质导数为0**。用链式法则展开分布函数的物质导数，我们得到

$$\frac{\mathrm{D}f}{\mathrm{D}t}=\frac{\partial f}{\partial t}+\dot{\mathbf{x}}\cdot\nabla_{\mathbf{x}}f+\dot{\mathbf{u}}\cdot\nabla_{\mathbf{u}}f=0$$ {#eq-DfDt}

代入$\dot{\mathbf{x}}=\mathbf{u}$, $\dot{\mathbf{u}}=\mathbf{a}$，得到

$$\boxed{\frac{\partial f}{\partial t} + \mathbf{u} \cdot \nabla_\mathbf{x} f + \mathbf{a} \cdot \nabla_\mathbf{u} f = 0}$$ {#eq-Vlasov}

这就是**Vlasov方程**。

上述是**无碰撞情形**。若考虑**碰撞**，相空间小体积元内粒子会有流入流出，将其表示成**净碰撞源项**：
$$(\frac{\mathrm{D}f}{\mathrm{D}t})_{\text{coll}} = (\frac{\mathrm{D}f}{\mathrm{D}t})_{\text{in}} - (\frac{\mathrm{D}f}{\mathrm{D}t})_{\text{out}}$$ {#eq-collisionsource}

@eq-Vlasov 也就变为：
$$\boxed{\frac{\partial f}{\partial t} + \mathbf{u} \cdot \nabla_\mathbf{x} f + \mathbf{a} \cdot \nabla_\mathbf{u} f = (\frac{\mathrm{D}f}{\mathrm{D}t})_{\text{coll}}}$$ {#eq-Boltzmann}

这就是**Boltzmann方程**。因此Vlasov方程也称为无碰撞Boltzmann方程。

### 二体碰撞
上一节我们引入了抽象的碰撞项，接下来我们要讨论如何具体地表征碰撞。

我们研究最理想化的**二体弹性碰撞**。该碰撞过程满足：

质量守恒：

$$
M=m_{1}+m_{2}=m_{1}^{\prime}+m_{2}^{\prime}
$$ {#eq-massconserve}

动量守恒：

$$
M\mathbf{V}=m_{1}\mathbf{u}_{1}+m_{2}\mathbf{u}_{2}=m_{1}\mathbf{u}_{1}^{\prime}+m_{2}\mathbf{u}_{2}^{\prime}
$$ {#eq-momentumconserve}

能量守恒：

$$
E=\frac{1}{2}m_{1}u_{1}^{2}+\frac{1}{2}m_{2}u_{2}^{2}=\frac{1}{2}m_{1}u_{1}^{\prime 2}+\frac{1}{2}m_{2}u_{2}^{\prime 2}
$$ {#eq-energyconserve}

注意我们研究的碰撞前后两个粒子的质量都是不变的，因此在 @eq-momentumconserve、@eq-energyconserve 中并没有使用$m_{1}^{\prime}$、$m_{2}^{\prime}$.

在 @eq-momentumconserve 中，我们引入了质心速度$\mathbf{V}$. 再引入两个新变量：

相对速度：

$$
\mathbf{v}=\mathbf{u}_{1}-\mathbf{u}_{2}
$$ {#eq-relativevelocity}

约化质量：

$$
\tilde{m}=\frac{m_{1}m_{2}}{m_{1}+m_{2}}
$$ {#eq-reducedmass}

于是有：

$$
\mathbf{u_{1}}=\mathbf{V}+\frac{m_{2}}{m_{1}+m_{2}}\mathbf{v}
$$ {#eq-u1}

$$
\mathbf{u_{2}}=\mathbf{V}-\frac{m_{1}}{m_{1}+m_{2}}\mathbf{v}
$$ {#eq-u2}

